### ISSUE TITLE
stuck on lock?

### ISSUE THREAD

**Issue by tyoc213** [stas00/ipyexperiments#4]
after almost all day and probably some hibernations...

I created an experiment just right after that tried to delete it...

![image](https://user-images.githubusercontent.com/506234/83343941-70540400-a2c6-11ea-9b9a-70304a42899c.png)

I ended hiting once the stop button on top of the ipynb.

**Comment by stas00** [comment]
Thank you for your report, @tyoc213. 

Yes, I see those occasionally. If you manage to create a reproducible test case please submit it and then it can be fixed.

Ideally I'd like to get rid of threads completely, as the current workaround is not only clunky, it's imprecise. I'm waiting for pytorch to implement support for [multiple torch.cuda.max_memory_allocated() counters](https://github.com/pytorch/pytorch/issues/16266). When this happens threads will no longer be needed. So please vote on that issue and perhaps it'll be looked at.
