### ISSUE TITLE
Fails on Colab with Error in callback <bound method CellLogger.post_run_cell of <ipyexperiments.cell_logger.CellLogger object >>

### ISSUE THREAD

**Issue by rahulraj80** [stas00/ipyexperiments#5]
Unable to even load it once. 
Minimum example to replicate the issue

[IN:1]
```
!pip install -q ipyexperiments
import ipyexperiments as ipye
print(ipye.__version__)
```
[OUT:1]
```
0.1.17
```
[IN:2]
```
exp1 = ipye.IPyExperimentsPytorch()
```
[OUT:2]
```
*** Experiment started with the Pytorch backend
Device: ID 0, Tesla K80 (11441 RAM)


*** Current state:
RAM:    Used    Free   Total       Util
CPU:   1,681  11,122  13,021 MB  12.92% 
GPU:     312  11,128  11,441 MB   2.73% 


Error in callback <bound method CellLogger.post_run_cell of <ipyexperiments.cell_logger.CellLogger object at 0x7fcd473018d0>> (for post_run_cell):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: post_run_cell() missing 1 required positional argument: 'result'
```

Similar failure with 
ipye.IPyExperimentsCPU()

Have a look here:
https://colab.research.google.com/gist/rahulraj80/0612b885c6fdf79b828fd38bfeb0e1f9/untitled1.ipynb

**Comment by rahulraj80** [comment]
Also tried after running the following, with no effect:
```
!pip install git+https://github.com/nicolargo/nvidia-ml-py3
```

**Comment by stas00** [comment]
Thank you for your report, @rahulraj80 

It looks like colab is running an old ipython (5.5.0) which doesn't support events:
https://github.com/googlecolab/colabtools/issues/891#issuecomment-562427698

You can upgrade it:
https://github.com/googlecolab/colabtools/issues/891#issuecomment-562426298

For posterity copying the full code from the above solution here:

```
!pip install -q --upgrade ipython
!pip install -q --upgrade ipykernel

# Restart with new IPython.
import os
import signal
os.kill(os.getpid(), signal.SIGTERM)
```

Run that cell, which will report a crash, then run your code normally. then everything works.

I will update the package requirements to ask for ipython >= 6.0.0

To check which ipython you have run:

```
import IPython

IPython.version_info
IPython.__version__
```
